#!/bin/bash

#https://docs.docker.com/docker-hub/builds/advanced/

if [ "$LATEST_TAG" == "$DOCKER_TAG" ] ; then
  tag=$DOCKER_REPO:latest
  docker tag $IMAGE_NAME $tag
  docker push $tag
fi

# if [ "latest" == "$DOCKER_TAG" ] ; then
#   tag=$DOCKER_REPO:$LATEST_TAG
#   docker tag $IMAGE_NAME $tag
#   docker push $tag
# fi
