# This is a basic workflow to help you get started with Actions

name: dockerhub:2020.0

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile20
          push: true
          tags: tamboraorg/creubuntu:2020.0, tamboraorg/creubuntu:latest 

      -
        name: Test
        run: |
          docker run ./tests/ubuntu-test.sh
      

