# This is a basic workflow to help you get started with Actions

name: dockerhub:2020.0

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string 1:00  weekly,Friday,1:00 #m h d/m m d/w 
    - cron:  '00 1 * * 5'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build for test
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile20
          push: true
          tags: credocker/creubuntu:check20 

      -
        name: Test
        run: |
          docker run credocker/creubuntu:check20 /cre/ubuntu-test.sh   

      -
        name: Build and push
        id: docker_push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile20
          push: true
          tags: credocker/creubuntu:2020.0, credocker/creubuntu:latest 

 

