# This is a basic workflow to help you get started with Actions

name: dockerhub:2022.0

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build for test
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile22
          push: true
          tags: tamboraorg/creubuntu:check22

      -
        name: Test
        run: |
          docker run tamboraorg/creubuntu:check22 /cre/ubuntu-test.sh  
      -
        name: Build and push
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile22
          push: true
          tags: tamboraorg/creubuntu:2022.0 

